### ISSUE TITLE
Should be the tick running as first callback?

### ISSUE THREAD

**Issue by mruz** [vakata/websocket#1]
I have `sleep(30);` in the tick (is it right?), so it's waiting before connect. Maybe move it at the end?

**Comment by vakata** [comment]
No need to sleep inside the tick, the server class handles this automatically - in fact - if you do not need the tick function - do not set it - that way the server class can optimize sleep times.

Best regards,
Ivan

**Comment by mruz** [comment]
OK. I want to send some data to all users by interval. So, I should use message for this?

**Comment by vakata** [comment]
The clean solution is to use `tick` but do not use sleep inside that function, as it is running on the server thread. Simply take note of the last time you sent a message and only send the next one if your interval has passed, at least that is how I use it.

Here is an example:

``` php
$last = 0;
$server
    ->onTick(function ($server) use (&$last, $tenders) {
        $cur = time();
        if ($cur - $last > 30) {
            // a message is sent to all clients every 30 seconds
            foreach ($server->getClients() as $client) {
                $server->send($client['socket'], "Message");
            }
            $last = $cur;
        }
    });
```
