### ISSUE TITLE
Upgrade to PHP 7.*

### ISSUE THREAD

**Issue by Byter09** [vakata/websocket#11]
I'm using this project for a bigger project of mine that uses websockets to update javascript clients. Sort of a close-to-real-time game interface if you will. As already seen in my last pull request, this project is not fully valid for PHP 7 anymore and will therefore have unexpected behaviour and/or produce exceptions. I thought instead of simply fixing everything and improving it only in my private repo, I'd simply share my changes.

I'm hereby proposing a full upgrade of this great library (I looked at like 4 before I found this, and it has NO dependencies AND is way faster because of using the built-in stream functionality instead of basic sockets (yes I know streams are based on them but optimized)).

In the next few days I'll make pull requests regarding static type hinting, using declare(strict_types=1) and changed default behaviour. I still require the full support of the owner to upgrade the library to PHP 7 as this will make it incompatible with every version below.

**Comment by vakata** [comment]
Thank you for taking the time to do this - I am all for upgrading to PHP 7, my only requirement is that we keep the minimum version to PHP 7.0, from what I gather this is what you mean too.

**Comment by Byter09** [comment]
I have no preference as to which PHP 7 version to use. I personally use 7.2.
PHP 7.1 has nullables, void functions, and smaller array improvements
PHP 7.2 has a object type (not need in this project), abstract method overriding (may used here?) and new socket functions: 

     socket_addrinfo_lookup()
     socket_addrinfo_connect()
     socket_addrinfo_bind()
     socket_addrinfo_explain()


But I'll set PhpStorm to PHP 7.0 so it'll tell me :)
