### ISSUE TITLE
Additional new functionality

### ISSUE THREAD

**Issue by Byter09** [vakata/websocket#12]
I'm proposing polishing and upgrading this library to become easier to use and allow faster integration.

What might be useful and what is not can be discussed in here.

For a start, I'd like to propose the following functionality:

- abstract user class so we can extend the user for project related additions and changes
- (optional) abstract the server class and make required functionality (connected() etc.) protected to allow inheriting and changing (instead of using callbacks)
- implement a protected broatcast() method to broadcast to all users
- implement a protected reply() method in the user object so onMessage() only has to give us the user
- implement easy to access methods for all clientData contents like IP, origin, requested language and so on

Further ideas will be added here by me. Please correct me if an idea is not fitting or simply not needed as I still work on my main project with this and I simply noticed missing functionality that might not actually be missing as this is a library.

**Comment by vakata** [comment]
All the ideas sound great - if you have any of those ready - create PRs. If not - let me know which are free to work on so that I can help.

If you prefer I could make the required code structure changes (with empty placeholders) and you can add the PRs then? 
It all depends on how far along you are with the implementation of those ideas.

**Comment by Byter09** [comment]
None of the given points are ready for a PR. These were all on my todo list in my own project. As I said, I just wanted to share before I do all this for myself only. Simply thought I'd do two things at once! 😄

Also, all of these tasks are free right now, because I wanted to wait for your approval as this is your library.
I'll work on getting composer running and read a bit about it. I'll see what comes up till then and redo my previous PR and then I'll see what's left to do I guess. If you're really quick I can also just scrap my PR and move on based on what you did till then.

**Comment by vakata** [comment]
Sounds like a plan - familiarize yourself with composer (you won't regret it), and in the mean time I will make a few changes and adjustments. 

I guess I will be done with all my changes by end of the day today - then you can check out the new code and start making PRs for anything that is missing. How does that sound?

**Comment by Byter09** [comment]
Great. This is the first real project on GitHub which I really like to support. Can't wait to get this going.

I'll set up composer in other projects as well then - until I hear something on here.
Also, I'll scrap my fork and refork. This should get rid of all the messy code on my end.

Quick question though: I'm using PhpStorm 2017.3. I usually tell it to cleanup, optimize and rearrange on commits. Should I disable this and tell it to use whatever it gets? And dont get me started on code style automation...

EDIT: Composer is already integrated and I could also activate PHP CodeSniffer related code inspection. My other project has like 400 warnings. This is great and bad at the same time 😐

**Comment by Byter09** [comment]
Even though I'm not a fan of PSR-2 I'll set my IDE to use it for this project. Is there a PSR for the style I used? (The one with tabs, { on the same line and several other small changes?)

Even the PHP documentation is not PSR-2 compliant.

**Comment by vakata** [comment]
v.2 has most of this.
