### ISSUE TITLE
Bad response

### ISSUE THREAD

**Issue by alexolliveira** [vakata/websocket#19]
Fatal error: Uncaught vakata\websocket\WebSocketException: Bad response in \vendor\vakata\websocket\src\Client.php:57
Warning: fsockopen(): unable to connect to 127.0.0.1:8080 vendor\vakata\websocket\src\Client.php on line 28

**Comment by vakata** [comment]
Seems like the server is not returning data that the client class supports. I only test the Client with the Server from the package, I cannot guarantee the Client is compatible with other websocket servers.
