### ISSUE TITLE
PHP Fatal error:  Uncaught vakata\websocket\WebSocketException: Bad response in /Users/17tech/wwwroot/test_workman/vendor/vakata/websocket/src/Client.php:56

### ISSUE THREAD

**Issue by zhangrenjie** [vakata/websocket#20]
PHP Fatal error:  Uncaught vakata\websocket\WebSocketException: Bad response in /Users/17tech/wwwroot/test_workman/vendor/vakata/websocket/src/Client.php:56
Stack trace:
#0 /Users/17tech/wwwroot/test_workman/TestClient1.php(5): vakata\websocket\Client->__construct('ws://127.0.0.1:...')
#1 {main}
  thrown in /Users/17tech/wwwroot/test_workman/vendor/vakata/websocket/src/Client.php on line 56

Fatal error: Uncaught vakata\websocket\WebSocketException: Bad response in /Users/17tech/wwwroot/test_workman/vendor/vakata/websocket/src/Client.php:56
Stack trace:
#0 /Users/17tech/wwwroot/test_workman/TestClient1.php(5): vakata\websocket\Client->__construct('ws://127.0.0.1:...')
#1 {main}
  thrown in /Users/17tech/wwwroot/test_workman/vendor/vakata/websocket/src/Client.php on line 56

**Comment by vakata** [comment]
Seems like the server is not returning data that the client class supports. I only test the Client with the Server from the package, I cannot guarantee the Client is compatible with other websocket servers.
