### ISSUE TITLE
Server::connected() doesn't shut down the socket if Server::callbacks['validate']  returns false.

### ISSUE THREAD

**Issue by smindel** [vakata/websocket#22]
Hi, awesome library, pure gold!

In `Server::connected()` I understand that if `Server::callbacks['validate']` returns `false`, the handshake is supposed to abort. I expect the connection to terminate, but it hangs. I think this is because the socket is not dropped explicitly, e.g.:

```
                $this->sendClear($socket, "HTTP/1.1 400 Bad Request\r\n\r\n");
                @stream_socket_shutdown($socket, STREAM_SHUT_RDWR);
                return false;
```
As a result the client stays connected, waiting for the server to complete the handshake, which never happens.

Is this a bug or how is this supposed to work?

Thanks

Andy

P.S.: I think it should be `$client->connect();` instead of `$client->run();` in the client example in the README.md. And all the docblocks in Server for setting callbacks say, they receive an assoc array of client data, while they actually receive ServerClient instances.

**Comment by vakata** [comment]
Glad you liked the lib! Thank you for the pointers about docblocks and examples - I corrected them. Let me know if the issue is resolved (I added an explicit socket shutdown).

**Comment by smindel** [comment]
Works like a charm, mate. Thanks heaps!

This lib is replacing a ReactPHP implementation in my project, because it's much lighter and straight forward.
