### ISSUE TITLE
Incoming msgs larger than Base::$fragmentSize break communication in Chrome and Edge

### ISSUE THREAD

**Issue by smindel** [vakata/websocket#23]
Hi vakata,

I m observing the following behavior:

When receiving messages exceeding Base::$fragmentSize from Chrome, the message callback is delayed by what appears to me as a timeout of 60 sec. Despite that timeout, the message is received in full. Subsequent messages sent back to Chrome are not received in the browser.

This works in FF as expected without the delay. Increasing Base::$fragmentSize to larger than the size of the message fixes the issue in Chrome.

It feels like exceeding the limit, keeps both sides from assuming valid states, which the PHP side is recovering from when reaching the timeout (i couldn't figure out which timeout that actually is...), but the Chrome side fails to resume communication via the affected connection.

I'd like to understand what is happening and why it works in one browser but not the other, rather than just upping Base::$fragmentSize, which doesn't seem to be supported atm. I m not sure if this is an issue with your lib or Chrome or FF. I m hoping that my report may ring a bell with you and you might be able to help me resolving my issue.

Thanks in advance

Andy

**Comment by vakata** [comment]
Thank you - just fixed it in 2.0.3

**Comment by smindel** [comment]
AWESOME !! That was quick. Works. Cheers, mate
