### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by mruz** [vakata/websocket#3]
Sometimes I'm getting:

> fwrite(): send of 1000 bytes failed with errno=32 Broken pipe

and server stops. 
I'm getting `broken pipe` also on other library.. Do you know what could be wrong (unsupported client, unexpected data)?

**Comment by vakata** [comment]
Sorry, I can not reproduce this. I am using this code in a few apps and I have never stumbled across this error. Have you tried inspecting `socket_last_error()`? 
Can you provide some steps to reproduce?

**Comment by mruz** [comment]
> supplied resource is not a valid Socket resource
I'll try to provide code to reproduce it.

----- Reply message -----
Od: "Ivan Bozhanov" <notifications@github.com>
Do: "vakata/websocket" <websocket@noreply.github.com>
DW: "Mariusz Łączak" <mruz@poczta.onet.pl>, "Author" <author@noreply.github.com>
Temat: [vakata/websocket] Broken pipe (#3)
Data: wt., maj 10, 2016 08:08

Sorry, I can not reproduce this. I am using this code in a few apps and I have never stumbled across this error. Have you tried inspecting socket_last_error()? 

Can you provide some steps to reproduce?

&mdash;You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by mruz** [comment]
Hmm, I did try to overwrite send:

``` php
public function send(&$socket, $data, $opcode = 'text', $masked = false)
    {
        while (strlen($data)) {
            $temp = substr($data, 0, static::$fragmentSize);
            $data = substr($data, static::$fragmentSize);
            $temp = $this->encode($temp, $opcode, $masked, strlen($data) === 0);
            try {
                fwrite($socket, $temp);
            } catch (\Exception $e) {
                $code = socket_last_error($socket);
                // log
                // ...
```

> socket_last_error(): supplied resource is not a valid Socket resource
> LOG: socket_last_error(Resource id #36)

**Comment by mruz** [comment]
Maybe something breaks a socket, so I added conditions for checking valid Socket resource, I'm waiting for some error:

``` php
try {
    if (is_resource($socket) && get_resource_type($socket) == "stream" && !feof($socket)) {
        if (fwrite($socket, $temp) === false) {
            return false;
        }
    } else {
        return false;
    }
} catch (\Exception $e) {
```

**Comment by vakata** [comment]
I am closing this and will reopen when further information is available.

**Comment by mruz** [comment]
I overwrite `send` method and it seems problem is gone.

``` php
public function send(&$socket, $data, $opcode = 'text', $masked = false)
    {
        while (strlen($data)) {
            $temp = substr($data, 0, static::$fragmentSize);
            $data = substr($data, static::$fragmentSize);
            $temp = $this->encode($temp, $opcode, $masked, strlen($data) === 0);

            if (is_resource($socket) && get_resource_type($socket) == "stream" && !feof($socket)) {
                if (stream_get_meta_data($socket)['timed_out'] || fwrite($socket, $temp) === false) {
                    return false;
                }
            } else {
                return false;
            }

            $opcode = 'continuation';
        }

        return true;
    }
```

**Comment by vakata** [comment]
I added this fix to the source, thanks @mruz
