### ISSUE TITLE
Websocket invalid frame header

### ISSUE THREAD

**Issue by mruz** [vakata/websocket#4]
On some browsers I'm getting `Websocket invalid frame header` and not connecting. Maybe it's related to encode header based on the payload size? http://stackoverflow.com/questions/8125507/how-can-i-send-and-receive-websocket-messages-on-the-server-side

**Comment by vakata** [comment]
I will investigate, it has never happened to me. I tested with 3MB messages, so I doubt it is the size header. But I will try to reproduce this - thanks for letting me know.

**Comment by vakata** [comment]
@mruz Could you please share a browser vendor and version, as I can not reproduce this?

**Comment by mruz** [comment]
It seems that #3 also fix this.
