### ISSUE TITLE
wss

### ISSUE THREAD

**Issue by mruz** [vakata/websocket#5]
Could you provide some example for secure connection? I generated cert by:

```
openssl req -x509 -nodes -days 3650 -newkey rsa:1024 -keyout wss.pem -out wss.pem
```

And did run a server:
$server = new Server($url, '../tmp/wss.pem');

but I can't connect by the wss and I'm getting:

> Error in connection establishment: net::ERR_TIMED_OUT

**Comment by vakata** [comment]
Make sure the URL starts with `wss` and that you are connecting to a `wss` URL with the same port you used on the server.
As for the certificate - I followed a guide online, the format is the public, then the private key, optionally followed by the CA chain. In my case it looks something like this:

```
Certificate:
    Data:
        Version: 3 (0x2)
        ...
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----

```

I hope this helps, I can only assure you it works properly, as I only use these classes in `wss` mode.

Best regards,
Ivan

**Comment by mruz** [comment]
URL starts with wss:

``` php
$url = 'wss://localhost:5001';
$server = new Server($url, '../tmp/wss.pem');
```

And I'm connecting to a wss:

``` js
var location = 'wss://localhost:5001';
var ws = new WebSocket(location);

ws.onopen = function(e) {
    alert('Connected to server ');
}
```

For ws it works.

**Comment by vakata** [comment]
Did you check your certificate, is it the same as I mentioned above? And also make sure the certificate is trusted and for the domain.

**Comment by mruz** [comment]
Yes, it is. I see it happens when I set `non-blocking` mode https://github.com/reactphp/react/issues/2:

``` php
stream_set_blocking($server->getServer(), false);
$server->run();
```

If I comment this line, works fine.

**Comment by vakata** [comment]
I am sorry but I only test my own client and server classes for compatibility, as well as all major browsers (as clients). 

As far as I understand you are using the client from this repo and trying to connect to a reactphp server? If so - interoperability with react has never been the idea behind those minimal classes here.

If I misunderstood - let me know and I will reopen.

Best regards,
Ivan

**Comment by mruz** [comment]
No, I'm using only your code. When I provide cert and trying to set `non-blocking` I'm getting similar issue to react's.

``` php
$server = new vakata\websocket\Server('wss://localhost:5001', '../tmp/wss.pem');
stream_set_blocking($server->getServer(), false);
$server->run();
```

so, wss works if I comment stream_set_blocking line.

**Comment by vakata** [comment]
Sorry, the code works as provided. Adding additional options to the socket is not something I will support - the server will work as it is (without adding this option). Keep in mind if you do not add a tick function to code will be optimized enough and will not cause additional CPU cycles and will use the network to get an interrupt.

Best regards,
Ivan

**Comment by mruz** [comment]
OK, I removed the `stream_set_blocking` and it connects and works. 

But occasionally I'm getting:

> stream_socket_accept(): SSL operation failed with code 1. OpenSSL Error messages: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number

or

> stream_socket_accept(): SSL: Handshake timed out

**Comment by vakata** [comment]
I will dig into those errors - it is not something that I have encountered - it may be openSSL version specific. Could you share your PHP / OpenSSL versions?

**Comment by mruz** [comment]
``` sh
#php -v
PHP 5.6.9 (cli)
#openssl version
OpenSSL 1.0.1k 8 Jan 2015
```

**Comment by mruz** [comment]
Could you reopen this issue? `PHP 5.6.24` and `OpenSSL 1.0.1k 8 Jan 2015` and I'm still getting:

> stream_socket_accept(): SSL operation failed with code 1. OpenSSL Error messages:
> error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number"
> var 1 string (65) "./vendor/vakata/websocket/src/Server.php[74]"

**Comment by vakata** [comment]
There is a lot of information regarding this error. It is nothing I can do on the PHP side. 

It is probably caused by an incompatible client/server SSL version, which would force a connection using unsupported protocols, which will cause a failure with the above error string. 

Read the first five results (don't worry they are not PHP related), there are even some commands you can run to determine the cause of the issue. What I am sure though is that it is not something I can fix with PHP code:
https://www.google.bg/#safe=off&q=error:1408F10B:SSL+routines:SSL3_GET_RECORD:wrong+version+number

**Comment by mruz** [comment]
I force `ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;` on nginx and now I only get:

> stream_socket_accept(): SSL: Handshake timed out
> ./vendor/vakata/websocket/src/Server.php[74]

I tried with `stream_set_timeout($server->getServer(), 10);` but no avail.

**Comment by rnaga** [comment]
I've recently made a TLS library and this probably helps resolve your issue.
[/rnaga/PHP-TLS](https://github.com/rnaga/PHP-TLS)

I can give you more details if you are interested.
