### ISSUE TITLE
can't receive unix signals while reading

### ISSUE THREAD

**Issue by sctt** [vakata/websocket#7]
Hello,

i'm using this library for a project which runs as a CLI daemon.
the problem is that the daemon cannot receive unix signals while the library is reading from its socket, and that cannot be tolerated by my requirements.

i solved by modifying the read method of Base.php class in this way:

```
[...]
  protected function read($length) {
    $data = '';
    $read = array($this->socket); $write = null; $except = null;
    while (strlen($data) < $length) {
      stream_select($read, $write, $except, null);
      $buffer = fread($this->socket, $length - strlen($data));
      if ($buffer === false) {
[...]
```

a warning will be raised after signal receiving, but that's intended behaviour:
http://php.net/manual/en/function.stream-select.php

i hope you will consider this improvement for your next release.

**Comment by vakata** [comment]
I am afraid I can't identify where this piece of code is. There is no `read` function in the `Base` trait, I could not find such a function in any of the other classes as well. Please provide more info and I will reopen.
