### ISSUE TITLE
Cannot drop connection to a client

### ISSUE THREAD

**Issue by mmowbray** [vakata/websocket#8]
Hello,

I am using this library and one feature I am missing is the ability to drop a connection with a connected client.

The approximate code I am trying to write would be:

```
$server->disconnect($client);
```

I noticed that [Server.php](https://github.com/vakata/websocket/blob/master/src/Server.php#L270l) has a protected method for this event, but I am not sure if simply making it accessible and calling it is the proper way to go about it.

Thanks!

**Comment by vakata** [comment]
You can use the `send` method - `$server->send($client, '', 'close')`
